import type { CodegenConfig } from "@graphql-codegen/cli";

import { loadEnv } from "vite";

const { WP_API, WP_AUTH_PASS, WP_AUTH_USER } = loadEnv(
  process.env.NODE_ENV ?? "development",
  process.cwd(),
  "",
);

const config: CodegenConfig = {
  documents: ["src/**/*.{graphql,js,ts,jsx,tsx}", "!src/gql/**/*", "!src/services/github/**/*"],
  generates: {
    "./schema.graphql": {
      config: {
        includeDirectives: true,
      },
      plugins: ["schema-ast"],
    },
    "./src/gql/": {
      config: {
        useTypeImports: true,
      },
      plugins: [],
      preset: "client",
    },
  },
  hooks: {
    // client-preset's fragment masking emits a phantom "$fragmentRefs" union arm for every
    // implementing type of a polymorphic interface (e.g. WPGraphQL's EditorBlock), including
    // block types our queries never select fields on — those arms reference Fragment names
    // that are never actually generated, which tsc reports as hundreds of false positives.
    // The generated file isn't hand-edited (regenerated by `pnpm gql:generate`), so silence
    // typechecking on it here rather than fight the codegen output.
    afterAllFileWrite: [
      "node -e \"const fs=require('fs');const f='src/gql/graphql.ts';const c=fs.readFileSync(f,'utf8');if(!c.startsWith('// @ts-nocheck'))fs.writeFileSync(f,'// @ts-nocheck\\n'+c);\"",
      "pnpm exec oxfmt .",
    ],
  },
  ignoreNoDocuments: true, // for better experience with the watcher
  schema: [
    {
      [WP_API]: {
        headers: {
          Authorization: `Basic ${Buffer.from(`${WP_AUTH_USER}:${WP_AUTH_PASS}`).toString("base64")}`,
        },
      },
    },
  ],
};

export default config;
