allowBuilds:
  "@parcel/watcher": set this to true or false
  "@sentry/cli": set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
