allowBuilds:
  "@infisical/cli": true
  "@parcel/watcher": true
  "@sentry/cli": true
  esbuild: true
  msw: false
  sharp: true
minimumReleaseAgeExclude:
  - "@infisical/cli@0.43.114"
  - "@playwright/test@1.62.0 || 1.62.1"
  - "@vue/devtools-api@8.2.1"
  - "@vue/devtools-kit@8.2.1"
  - "@vue/devtools-shared@8.2.1"
  - playwright-core@1.62.0 || 1.62.1
  - playwright@1.62.0 || 1.62.1
  - sass@1.102.0
  - vite@8.2.0 || 8.2.1
  - '@astrojs/node@11.1.0 || 11.1.2'
  - "@astrojs/vue@7.0.2"
  - astro@7.2.0 || 7.2.2
  - rollup-plugin-visualizer@7.1.1
  - '@faker-js/faker@10.6.0'
  - tm-themes@1.12.6
