name: Unit tests
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  VITEST_CI: true

jobs:
  lint:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v7

      - name: Fetch secrets from Infisical 🔐
        uses: Infisical/secrets-action@77ab1f4ccd183a543cb5b42435fbd181189f4995 # v1.0.16
        with:
          method: "oidc"
          identity-id: "8938f75a-fe73-4688-a8ed-e12dc90e6c0f"
          project-slug: "web-shaped"
          env-slug: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          domain: "https://infisical.kasimir.dev"

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies 🛠️
        run: pnpm i --frozen-lockfile

      - name: Run Vitest (with coverage and JUnit report) 🧪
        run: pnpm run test:unit:ci
        env:
          SITE_URL: "http://localhost:4321"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          directory: ./tests/unit/coverage
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7.0.0
        with:
          report_type: test_results
          files: ./test-report.junit.xml
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}
